apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: cabotage
  namespace: postgres
  labels:
    cabotage.io/infra: "true"
spec:
  inheritedMetadata:
    labels:
      cabotage.io/infra: "true"
  instances: 2
  certificates:
    serverTLSSecret: cabotage-tls
    serverCASecret: operators-ca-crt
  storage:
    size: 1Gi
