apiVersion: v1
kind: ConfigMap
metadata:
  namespace: cabotage
  name: registry-config
data:
  config.yml: |
    version: 0.1
    auth:
      token:
        realm: https://cabotage-app.cabotage.svc.cluster.local:443/docker/auth
        service: cabotage-registry
        issuer: cabotage-app
        rootcertbundle: /etc/docker/registry-signing/public_key_bundle
    log:
      level: info
      fields:
        service: registry
    storage:
      cache:
        blobdescriptor: inmemory
      redirect:
        disable: true
      delete:
        enabled: true
      s3:
        region: us-east-2
        regionendpoint: https://rustfs.cabotage.svc.cluster.local:9000
        bucket: cabotage-registry
        encrypt: false
        secure: true
        v4auth: true
        chunksize: "5242880"
    http:
      addr: 0.0.0.0:4999
      host: https://registry.cabotage.svc.cluster.local:5000
      headers:
        X-Content-Type-Options: [nosniff]
