apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: enrollment-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cabotage-enrollment-operator-clusterrole
subjects:
- kind: ServiceAccount
  namespace: cabotage
  name: enrollment-operator
