#!/bin/sh
set -e

. "$(dirname "$0")/_lib.sh"

# Signs intermediate CA CertificateRequests generated by cert-manager
# using the local root CA key. Updates the K8s secrets with the signed
# cert chain.

TMPDIR=$(mktemp -d)
trap "rm -rf $TMPDIR" EXIT

cat > "$TMPDIR/ext.cnf" <<EOF
basicConstraints = critical, CA:TRUE, pathlen:0
keyUsage = critical, digitalSignature, keyCertSign, cRLSign
EOF

CA_CERT_FILE="${CA_CERT_FILE:-$CA_CERT_FILE}"

for ca_name in certificate-approver-ca operators-ca; do
  SECRET_NAME="${ca_name}-key-pair"

  # Check if already signed by our current root CA (verify first cert in chain only)
  existing_cert=$($KUBECTL get secret "$SECRET_NAME" -n cert-manager \
    -o jsonpath='{.data.tls\.crt}' 2>/dev/null | base64 -d 2>/dev/null || echo "")
  if [ -n "$existing_cert" ]; then
    # Extract only the first certificate (the intermediate), not the full chain
    first_cert=$(printf '%s' "$existing_cert" | awk '/BEGIN CERT/,/END CERT/{print; if(/END CERT/) exit}')
    if printf '%s' "$first_cert" | openssl verify -partial_chain -CAfile "$CA_CERT_FILE" > /dev/null 2>&1; then
      echo "$ca_name already signed by current root CA."
      continue
    fi
    echo "$ca_name secret exists but was signed by a different root CA. Deleting..."
    $KUBECTL delete secret "$SECRET_NAME" -n cert-manager
    $KUBECTL delete certificaterequest -n cert-manager -l cert-manager.io/certificate-name="$ca_name" 2>/dev/null || true
    sleep 5
  fi

  # Wait for cert-manager to create a CertificateRequest (name prefixed with certificate name)
  echo "Waiting for $ca_name CertificateRequest..."
  CR_NAME=""
  for attempt in $(seq 1 60); do
    CR_NAME=$($KUBECTL get certificaterequest -n cert-manager \
      --sort-by=.metadata.creationTimestamp \
      -o jsonpath="{.items[?(@.metadata.ownerReferences[0].name==\"$ca_name\")].metadata.name}" 2>/dev/null | awk '{print $NF}')
    if [ -n "$CR_NAME" ]; then break; fi
    sleep 2
  done
  if [ -z "$CR_NAME" ]; then
    echo "Timed out waiting for $ca_name CertificateRequest."
    exit 1
  fi

  # Wait for cert-manager to create the secret
  echo "Waiting for secret $SECRET_NAME..."
  for _sw in $(seq 1 30); do
    $KUBECTL get secret "$SECRET_NAME" -n cert-manager > /dev/null 2>&1 && break
    sleep 2
  done

  # Extract CSR from CertificateRequest
  echo "Signing $ca_name with root CA..."
  $KUBECTL get certificaterequest "$CR_NAME" -n cert-manager \
    -o jsonpath='{.spec.request}' | base64 -d > "$TMPDIR/int.csr"

  # Sign with root CA
  openssl x509 -req -in "$TMPDIR/int.csr" \
    -CA "$CA_CERT_FILE" -CAkey "$SECRETS_DIR/ca.key" -CAcreateserial \
    -out "$TMPDIR/int.crt" -days 1825 -extfile "$TMPDIR/ext.cnf" 2>/dev/null

  # Build chain (intermediate + root)
  cat "$TMPDIR/int.crt" "$CA_CERT_FILE" > "$TMPDIR/chain.crt"

  # Update the secret with the properly-signed cert chain
  CHAIN_B64=$(base64 < "$TMPDIR/chain.crt" | tr -d '\n')
  ROOT_B64=$(base64 < "$CA_CERT_FILE" | tr -d '\n')
  $KUBECTL patch secret "$SECRET_NAME" -n cert-manager --type merge \
    -p "{\"data\":{\"tls.crt\":\"$CHAIN_B64\",\"ca.crt\":\"$ROOT_B64\"}}"

  # For operators-ca, also create a separate ca-crt secret (used by CNPG, Redis, etc.)
  if [ "$ca_name" = "operators-ca" ]; then
    $KUBECTL create secret generic operators-ca-crt -n cert-manager \
      --from-file=ca.crt="$TMPDIR/chain.crt" \
      --dry-run=client -o yaml | $KUBECTL apply -f -
    echo "operators-ca-crt secret created/updated in cert-manager namespace."
  fi

  echo "$ca_name signed and updated."
done

echo "All intermediate CAs signed."
