apiVersion: v1
kind: Service
metadata:
  namespace: cabotage
  name: seaweedfs-master
  labels:
    app: seaweedfs
    component: master
    cabotage.io/infra: "true"
spec:
  clusterIP: None
  ports:
    - port: 9333
      name: http
    - port: 19333
      name: grpc
  selector:
    app: seaweedfs
    component: master
  publishNotReadyAddresses: true
