apiVersion: v1
kind: Service
metadata:
  namespace: cabotage
  name: seaweedfs
  labels:
    app: seaweedfs
    cabotage.io/infra: "true"
spec:
  clusterIP: None
  ports:
    - port: 9000
      name: s3
      targetPort: 9000
  selector:
    app: seaweedfs
    component: s3
  publishNotReadyAddresses: true
