apiVersion: v1
kind: Service
metadata:
  namespace: cabotage
  name: rustfs
  labels:
    app: rustfs
spec:
  clusterIP: None
  ports:
    - port: 9000
      name: rustfs
  selector:
    app: rustfs
  publishNotReadyAddresses: true
