apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: cabotage
  name: cabotage-app-worker
  labels:
    app: cabotage-app
    component: worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cabotage-app
      component: worker
  template:
    metadata:
      labels:
        app: cabotage-app
        component: worker
        ca-admission.cabotage.io: "true"
    spec:
      serviceAccountName: cabotage-app
      initContainers:
        - name: cabotage-enroller
          image: cabotage/sidecar:4
          imagePullPolicy: Always
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          args:
            - "kube-login"
            - "--namespace=$(NAMESPACE)"
            - "--vault-auth-kubernetes-role=cabotage-cabotage-app"
            - "--fetch-consul-token"
            - "--vault-consul-role=cabotage-cabotage-app"
            - "--fetch-cert"
            - "--vault-pki-role=cabotage-cabotage-app"
            - "--pod-name=$(POD_NAME)"
            - "--pod-ip=$(POD_IP)"
            - "--service-names=cabotage-app"
            - "--additional-dns-names=localhost"
          volumeMounts:
            - name: vault-secrets
              mountPath: /var/run/secrets/vault
      containers:
        - name: cabotage-sidecar
          image: cabotage/sidecar:4
          imagePullPolicy: Always
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          args:
            - "maintain"
          volumeMounts:
            - name: vault-secrets
              mountPath: /var/run/secrets/vault
        - name: cabotage-app-worker
          image: ghcr.io/cabotage/cabotage-app:latest
          imagePullPolicy: Always
          command: ["celery"]
          args:
            - "-A"
            - "cabotage.celery.worker.celery_app"
            - "worker"
            - "-l"
            - "info"
            - "-E"
          envFrom:
            - configMapRef:
                name: cabotage-config
          env:
            - name: CABOTAGE_SQLALCHEMY_DATABASE_URI
              valueFrom:
                secretKeyRef:
                  name: cabotage-app-secrets
                  key: database-uri
            - name: CABOTAGE_CELERY_BROKER_URL
              valueFrom:
                secretKeyRef:
                  name: cabotage-app-secrets
                  key: redis-uri
            - name: CABOTAGE_CELERY_RESULT_BACKEND
              valueFrom:
                secretKeyRef:
                  name: cabotage-app-secrets
                  key: redis-uri
            - name: CABOTAGE_MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: rustfs-cabotage-registry
                  key: access-key-id
            - name: CABOTAGE_MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: rustfs-cabotage-registry
                  key: secret-key
            - name: CABOTAGE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: cabotage-app-secrets
                  key: secret-key
            - name: CABOTAGE_SECURITY_PASSWORD_SALT
              valueFrom:
                secretKeyRef:
                  name: cabotage-app-secrets
                  key: password-salt
            - name: CABOTAGE_REGISTRY_AUTH_SECRET
              valueFrom:
                secretKeyRef:
                  name: cabotage-app-secrets
                  key: registry-auth-secret
          volumeMounts:
            - name: vault-secrets
              mountPath: /var/run/secrets/vault
          resources:
            limits:
              cpu: 400m
              memory: 1200Mi
            requests:
              cpu: 200m
              memory: 600Mi
      volumes:
        - name: vault-secrets
          emptyDir:
            medium: "Memory"
            sizeLimit: "1M"
