apiVersion: v1
kind: Service
metadata:
  name: alert-echo
  namespace: cabotage
  labels:
    app: alert-echo
spec:
  ports:
  - name: http
    port: 8090
    targetPort: http
  selector:
    app: alert-echo
